apiVersion: v1
kind: Service
metadata:
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  type: LoadBalancer
#  loadBalancerIP: X.X.X.X
